balanced_mixup:
  alpha: 0.2
  enabled: false
cb_beta: 0.9999
curriculum:
  bm_end: 1.0
  bm_start: 0.5
  debug_epochs: 10
  early_stopping_patience: 5
  enabled: true
  epochs: 20
  learning_rate: 0.001
  lesion_end: 1.0
  lesion_start: 0.5
  metadata_path: /home/parkhomenko/Documents/new_project/datasets/metadata/unified_augmented.csv
  model_save_dir: saved_models/lesion_type
  train_features_dir: data/processed/features/train_skinonly
  val_features_dir: data/processed/features/val_skinonly
  val_metadata_path: /home/parkhomenko/Documents/new_project/datasets/metadata/unified_augmented.csv
  wandb:
    name: lesion_type_5percent
    project: skin_lesion_classification
    tags:
    - lesion_type
    - small_subset
  weight_decay: 0.01
data:
  datasets:
    dtd:
      root_dir: dtd/images
    isic2020:
      metadata:
        duplicates: metadata/ISIC_2020_Training_Duplicates.csv
        test_labels: metadata/ISIC_2020_Test_Metadata.csv
        train_labels: metadata/ISIC_2020_Training_GroundTruth_v2.csv
      test_dir: isic2020/ISIC_2020_Test_JPEG
      train_dir: isic2020/ISIC_2020_Training_JPEG
  processed:
    features_dir: features
    root_dir: /home/parkhomenko/Documents/new_project/data/processed
  root_dir: /home/parkhomenko/Documents/new_project/data
data_preprocessing:
  augmentations:
    flip_horizontal: true
    rotations:
    - 90
    - 180
    - 270
  image_size: 512
evaluation:
  metrics:
  - accuracy
  - f1_score
  - auroc
  save_results:
    auc_curves: true
    confusion_matrices: true
    mask_visualizations: true
    tsne_umap: true
focal_gamma: 2.0
lesion_loss_fn: lmf
models:
  mlp1:
    dropout: 0.3
    hidden_dims:
    - 512
    - 256
    input_dim: 256
    name: skin_not_skin_head
    output_dim: 2
  mlp2:
    dropout: 0.3
    hidden_dims:
    - 512
    - 256
    input_dim: 256
    name: lesion_type_head
    output_dim: 8
  mlp3:
    dropout: 0.3
    hidden_dims:
    - 512
    - 256
    input_dim: 256
    name: benign_malignant_head
    output_dim: 2
odin:
  enabled: false
<<<<<<< Updated upstream
  epsilon: 0.001
  temperature: 1000.0
=======
>>>>>>> Stashed changes
paths:
  isic_train: data/isic2020/ISIC_2020_Training_JPEG/train
  processed: data/processed/isic2020
sam:
  encoder:
    checkpoint_dir: saved_models/sam
    checkpoint_urls:
      vit_b: https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
      vit_h: https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
      vit_l: https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth
    freeze: true
    image_size: 1024
    pretrained: true
    type: vit_h
  mask_filtering:
    max_area_ratio: 0.8
    overlap_threshold: 0.95
    prefer_fewer_blobs: true
  prompting:
    points_per_image: 2
training:
  batch_size: 16
  class_names:
  - melanoma
  - nevus
  - basal_cell_carcinoma
  - squamous_cell_carcinoma
  - seborrheic_keratosis
  - actinic_keratosis
  - dermatofibroma
  - vascular
  class_weights:
  - 1.5
  - 1.5
  - 1.5
  - 1.2
  - 1.2
  - 1.5
  - 1.2
  - 1.2
  data_fraction: 1
  device: cuda
  max_samples_per_class: 2000
  model:
    dropout: 0.3
    hidden_dims:
    - 512
    - 256
  num_epochs: 50
  num_workers: 0
  pin_memory: true
  seed: 42
visualization:
  save_dir: results
  subdirs:
    auc_curves: auc_curves
    confusion_matrices: confusion_matrices
    mask_visualizations: mask_visualizations
    tsne_umap_embeddings: tsne_umap_embeddings
